/**
 * Responsive image sources.
 *
 * Every original in src/assets/images (name.jpg) has AVIF and WebP renditions next to it at a few widths
 * (name-480.avif, name-800.webp, ...), generated by scripts/images.mjs. Vite hashes all of them into /assets,
 * so they can be cached forever, and this module turns the hashed URLs back into srcset strings.
 */
const urls = import.meta.glob<string>("../assets/images/*.{avif,webp,jpg}", {
  eager: true,
  query: "?url",
  import: "default"
});

/** Intrinsic size of each original, so the <img> reserves its box before the file arrives. */
export const images = {
  lawata: { width: 1600, height: 1000 },
  synth: { width: 1600, height: 781 },
  fewes: { width: 1600, height: 774 },
  portrait: { width: 1200, height: 1600 }
} as const;

export type ImageName = keyof typeof images;

const renditions = (name: ImageName, ext: "avif" | "webp") =>
  Object.entries(urls)
    .filter(([file]) => file.includes(`/${name}-`) && file.endsWith(`.${ext}`))
    .map(([file, url]) => ({ width: Number(file.match(/-(\d+)\.\w+$/)?.[1]), url }))
    .sort((a, b) => a.width - b.width)
    .map(({ width, url }) => `${url} ${width}w`)
    .join(", ");

export const imageSet = (name: ImageName) => ({
  ...images[name],
  avif: renditions(name, "avif"),
  webp: renditions(name, "webp"),
  src: urls[`../assets/images/${name}.jpg`]
});
