/**
 * Regenerates src/data/marks.ts: the monochrome brand marks shown in the stack strip.
 *
 * Marks are fetched once from the Iconify API and stored as plain path data, so the site ships no icon
 * runtime and makes no third-party requests. Multi-tone marks keep their layers as opacities of the
 * current colour. Sources: Simple Icons and gilbarbara/logos (CC0), Material Design Icons (Apache-2.0),
 * selfh.st/icons and Streamline Logos (CC BY 4.0); the rest are drawn here. Logos remain trademarks of
 * their owners.
 *
 *   node scripts/marks.mjs
 */
import { writeFile } from "node:fs/promises";

const API = "https://api.iconify.design";
const OUT = new URL("../src/data/marks.ts", import.meta.url);

/**
 * Stack item -> Iconify icon (or inline drawing), brand tint for hover, optional fill -> opacity map, and an
 * optional `crop`: the viewBox of the ink alone (from getBBox, plus a hair of padding) for marks that sit
 * inside a padded artboard, so every mark renders at the same cap height.
 */
const table = {
  Python: { icon: "simple-icons:python", tint: "#3776ab" },
  PowerShell: { icon: "mdi:powershell", tint: "#5391fe", crop: "1.3 3.8 21.5 16.4" },
  "Power Automate": { icon: "selfhst:microsoft-power-automate-dark", tint: "#0066ff", crop: "0 50 512 411" },
  AWS: { icon: "mdi:aws", tint: "#ff9900", crop: "1.8 5.8 20.4 12.4" },
  "Microsoft 365": { icon: "selfhst:microsoft-365-dark", tint: "#d83b01", crop: "22 0 468 512" },
  "Microsoft Graph": {
    tint: "#0078d4",
    viewBox: "0 0 24 24",
    crop: "1.2 2.7 21.6 19.1",
    paths: [
      { d: circle(12, 12, 3.2) },
      { d: circle(4.5, 7, 2.2) },
      { d: circle(19.5, 6, 2.2) },
      { d: circle(18.5, 18.5, 2.2) },
      { d: circle(6, 18, 2.2) },
      { d: "M9.3 10.4 6.4 8.2M14.7 9.9l3-2.6M14.4 14.2l2.7 2.9M9.7 14.3l-2.4 2.4", stroke: 1.8 }
    ]
  },
  SharePoint: { icon: "streamline-logos:microsoft-sharepoint-logo-solid", tint: "#036c70", crop: "0.8 0.8 22.4 22.4" },
  "Entra ID": {
    icon: "selfhst:microsoft-entra-id",
    tint: "#0f6cbd",
    crop: "0 26 512 460",
    layers: { "#225086": 1, "#074793": 0.92, "#0294e4": 0.78, "#6df": 0.55, "#96bcc2": 0.42, "#cbf8ff": 0.3 }
  },
  Zabbix: { icon: "selfhst:zabbix-dark", tint: "#d40000" },
  Wazuh: { icon: "selfhst:wazuh-dark", tint: "#3585f9", crop: "0 100 512 311" },
  Graylog: { icon: "simple-icons:graylog", tint: "#ff3633" },
  "Power BI": {
    tint: "#e2b400",
    viewBox: "0 0 24 24",
    crop: "1.8 1.8 20.4 20.4",
    paths: [{ d: roundedRect(2, 14, 6, 8, 1.25) }, { d: roundedRect(9, 8, 6, 14, 1.25) }, { d: roundedRect(16, 2, 6, 20, 1.25) }]
  },
  TypeScript: { icon: "simple-icons:typescript", tint: "#3178c6" },
  "Node.js": { icon: "simple-icons:nodedotjs", tint: "#5fa04e" },
  React: { icon: "simple-icons:react", tint: "#149eca", crop: "0 1.1 24 21.8" },
  "REST APIs": {
    viewBox: "0 0 24 24",
    crop: "1.8 1.8 20.4 20.4",
    paths: [
      { d: "M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1", stroke: 2 },
      { d: "M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1", stroke: 2 }
    ]
  },
  MySQL: { icon: "logos:mysql-icon", tint: "#4479a1" },
  Selenium: { icon: "simple-icons:selenium", tint: "#43b02a" },
  Docker: { icon: "simple-icons:docker", tint: "#2496ed", crop: "0 3.2 24 17.6" },
  Git: { icon: "simple-icons:git", tint: "#f05032" }
};

function circle(cx, cy, r) {
  return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${r * 2} 0a${r} ${r} 0 1 0 ${-r * 2} 0z`;
}

function roundedRect(x, y, w, h, r) {
  return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}z`;
}

const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1];

async function fetchMark(icon, layers = {}) {
  const [prefix, name] = icon.split(":");
  const res = await fetch(`${API}/${prefix}/${name}.svg`);
  if (!res.ok) throw new Error(`${icon}: HTTP ${res.status}`);
  const svg = await res.text();
  const viewBox = attr(svg, "viewBox");
  const paths = [...svg.matchAll(/<path\b[^>]*>/g)].map(([tag]) => {
    const fill = attr(tag, "fill");
    if (fill === "none") return null;
    const path = { d: attr(tag, "d") };
    const opacity = fill in layers ? layers[fill] : Number(attr(tag, "opacity") ?? 1);
    if (opacity !== 1) path.opacity = opacity;
    if (attr(tag, "fill-rule") === "evenodd") path.evenOdd = true;
    return path;
  });
  if (!viewBox || !paths.length) throw new Error(`${icon}: no paths`);
  return { viewBox, paths: paths.filter(Boolean) };
}

const lines = [
  "/* Generated by scripts/marks.mjs. Do not edit by hand. */",
  "",
  "export type MarkPath = { d: string; opacity?: number; evenOdd?: boolean; stroke?: number };",
  "",
  "/** A brand mark drawn in the current colour; `tint` is the brand colour used on hover. */",
  "export type Mark = { source: string; tint?: string; viewBox: string; paths: MarkPath[] };",
  "",
  "export const marks: Record<string, Mark> = {"
];
const formatPath = (p) => {
  const parts = [`d: ${JSON.stringify(p.d)}`];
  if (p.opacity !== undefined) parts.push(`opacity: ${p.opacity}`);
  if (p.evenOdd) parts.push("evenOdd: true");
  if (p.stroke) parts.push(`stroke: ${p.stroke}`);
  return `      { ${parts.join(", ")} }`;
};

const entries = Object.entries(table);
for (const [i, [name, spec]] of entries.entries()) {
  const mark = spec.icon ? await fetchMark(spec.icon, spec.layers) : { viewBox: spec.viewBox, paths: spec.paths };
  const source = spec.icon ?? "drawn in-house";
  const key = /^[A-Za-z_]\w*$/.test(name) ? name : JSON.stringify(name);
  const tint = spec.tint ? `tint: ${JSON.stringify(spec.tint)}, ` : "";
  lines.push(
    `  ${key}: {`,
    `    source: ${JSON.stringify(source)},`,
    `    ${tint}viewBox: ${JSON.stringify(spec.crop ?? mark.viewBox)},`,
    "    paths: [",
    mark.paths.map(formatPath).join(",\n"),
    "    ]",
    `  }${i < entries.length - 1 ? "," : ""}`
  );
  console.log(`${name.padEnd(16)} ${source.padEnd(50)} ${mark.paths.length} path(s)`);
}
lines.push("};", "");
await writeFile(OUT, lines.join("\n"));
console.log(`\nwrote ${OUT.pathname}`);
